import HassePrinciple.Padics.Squares
import HassePrinciple.QuadraticForm.Basic
import HassePrinciple.QuadraticForm.HasseMinkowski
import HassePrinciple.QuadraticForm.HighRank
import HassePrinciple.QuadraticForm.HilbertSymbol
import HassePrinciple.QuadraticForm.RankFour
import HassePrinciple.QuadraticForm.RankThree
